blog/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from posts.urls import router as posts_router
from user_management.urls import router as user_management_router

router = routers.DefaultRouter()
router.registry.extend(posts_router.registry)
router.registry.extend(user_management_router.registry)

urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "swagger/",
        SpectacularSwaggerView.as_view(
            template_name="swagger-ui.html", url_name="schema"
        ),
        name="swagger-ui",
    ),
    path('api/', include(router.urls), name='api'),
    path('admin/', admin.site.urls),
    path('auth/', include('dj_rest_auth.urls')),
    path('', include('posts.urls')),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

from user_management.urls import router as user_management_router

router = routers.DefaultRouter()
router.registry.extend(user_management_router.registry)

urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "swagger/",
        SpectacularSwaggerView.as_view(
            template_name="swagger-ui.html", url_name="schema"
        ),
        name="swagger-ui",
    ),
    path('api/', include(router.urls), name='api'),
    path('admin/', admin.site.urls),
    path('auth/', include('dj_rest_auth.urls')),
]

core/user_management/urls.py
from rest_framework import routers

from user_management.views import UserViewSet, GroupViewSet

router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"groups", GroupViewSet)

posts/urls.py
from django.urls import path
from rest_framework import routers

from posts.views import ListBlogPosts, CreateBlogPost, UpdateBlogPost, \
    ShowBlogPost, DeleteBlogPost, ListBlogPostsAPI

router = routers.DefaultRouter()
router.register('posts-list', ListBlogPostsAPI)


app_name = "posts"
urlpatterns = [
    path('', ListBlogPosts.as_view(), name="home"),
    path('create/', CreateBlogPost.as_view(), name="create-post"),
    path('update/<str:slug>/', UpdateBlogPost.as_view(), name="update-post"),
    path('delete/<str:slug>/', DeleteBlogPost.as_view(), name="delete-post"),
    path('<str:slug>/', ShowBlogPost.as_view(), name="show-post"),
]

core/user_management/models.py
from django.db import models

# Create your models here.

posts/models.py
from typing import Optional

from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    """New BlogPost model."""

    title = models.CharField(max_length=255, unique=True, verbose_name="Title")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                               blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Published")
    content = models.TextField(blank=True, verbose_name="Content")

    class Meta:
        """
        Override Meta class.

        ordering: ordering on field created_on
        verbose_name: Application name is Article
        """

        ordering = ['-created_on']
        verbose_name = 'Post'

    def __str__(self):
        """Display title in Django admin."""
        return self.title

    def save(self, *args, **kwargs):
        """Create a slug with slugify based on title."""
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def author_or_default(self) -> str:
        """Get author or return unknown."""
        return self.author.username if self.author else "unknown"

    @staticmethod
    def get_absolute_url() -> Optional[str]:
        """
        Get the absolute url for redirection.

        see: posts.urls.py
        app_name:name

        """
        return reverse("posts:home")

user_management/models.py
# Create your models here.

core/user_management/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from user_management.serializer import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [IsAuthenticated]

posts/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, \
    DetailView, DeleteView
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from posts.models import BlogPost
from posts.serializers import Serializer


class ListBlogPostsAPI(viewsets.ModelViewSet):
    """ListBlogPostsAPI."""

    queryset = BlogPost.objects.all()
    serializer_class = Serializer
    permission_classes = (IsAuthenticated, )
    filterset_fields = ['author', 'published']
    search_fields = ['title', 'content']


class ListBlogPosts(ListView):
    """ListBlogPosts."""

    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


@method_decorator(login_required, name='dispatch')
class CreateBlogPost(CreateView):
    """CreateBlogPost."""

    model = BlogPost
    template_name = "posts/blogpost_create.html"
    fields = ["title", "content"]


@method_decorator(login_required, name='dispatch')
class UpdateBlogPost(UpdateView):
    """UpdateBlogPost."""

    model = BlogPost
    template_name = "posts/blogpost_update.html"
    fields = ["title", "content", "published"]


class ShowBlogPost(DetailView):
    """ShowBlogPost."""

    model = BlogPost
    context_object_name = "post"
    template_name = "posts/blogpost_show.html"


@method_decorator(login_required, name='dispatch')
class DeleteBlogPost(DeleteView):
    """ShowBlogPost."""

    model = BlogPost
    context_object_name = "post"
    template_name = "posts/blogpost_delete.html"
    success_url = reverse_lazy("posts:home")

user_management/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from user_management.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [IsAuthenticated]

core/templates/swagger-ui.html
<!DOCTYPE html>
<html>

<head>
    <title>Swagger</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css">
</head>

<body>
<div id="swagger-ui"></div>
<script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
<script>
    const ui = SwaggerUIBundle({
        url: "{% url 'schema' %}",
        dom_id: '#swagger-ui',
        presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
            request.headers['X-CSRFToken'] = "{{ csrf_token }}"
            return request;
        }
    })
</script>
</body>

</html>

posts/templates/posts/blogpost_create.html
{% extends 'core.html' %}

{% block title %}
    <title>Create a post</title>
{% endblock %}

{% block content %}
    <h1>Create a post</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

posts/templates/posts/blogpost_delete.html
{% extends 'core.html' %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
    <h1>Delete {{ post.title }}</h1>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Yes, Delete">
    </form>
{% endblock %}

posts/templates/posts/blogpost_list.html
{% extends 'core.html' %}

{% block title %}
    <title>Home blog</title>
{% endblock %}

{% block content %}
    <h1>Test blog</h1>

    {% for post in posts %}
        <article>
            <h2>{{ post.title }}</h2>

                {% if request.user.is_authenticated %}
                    <div>
                        <a href="{% url 'posts:update-post' slug=post.slug %}">Update post</a>
                        <a href="{% url 'posts:delete-post' slug=post.slug %}">Delete post</a>
                    </div>
                {% endif %}

            <h5>published by <i>{{ post.author_or_default }}</i> on {{ post.created_on|date:'j F Y' }}</h5>
            <p>{{ post.content|safe|truncatewords:50 }}</p>

            <form action="{% url 'posts:show-post' slug=post.slug %}">
                <button>Read post</button>
            </form>
        </article>
    {% endfor %}
{% endblock %}

posts/templates/posts/blogpost_show.html
{% extends 'core.html' %}

{% block title %}
<title>{{ post.title }} </title>
{% endblock %}

{% block content %}
    <article>
        <h1>{{ post.title }}</h1>
        <h5>published by <i>{{ post.author_or_default }}</i> on {{ post.created_on|date:'j F Y' }}</h5>
        <br>
        <div>{{ post.content|linebreaks|safe }}</div>
    </article>
{% endblock %}

posts/templates/posts/blogpost_update.html
{% extends 'core.html' %}

{% block title %}
    <title>Update a post</title>
{% endblock %}

{% block content %}
    <h1>Update a post</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

posts/templates/posts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/core.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <a href="{% url 'posts:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create-post' %}">Create a post</a>
        {% endif %}
    </nav>

    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>